BASE_URL=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
ADMIN_URL=https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers

APP_USERNAME=Admin
APP_PASSWORD=admin123

ADMIN_USERNAME=Admin
ADMIN_PASSWORD=admin123

ESS_FIRST_NAME=FN_ESS
ESS_LAST_NAME=LN_ESS
ESS_USER_ID=ESS3145
ESS_USERNAME=ESSuser1
ESS_PASSWORD=ESSpassword123

view_personal_details.path=**/viewPersonalDetails/**
auth_login.path=**/auth/login**
dashboard.path=**/dashboard/**
admin_view_systems_users.path=**/admin/viewSystemUsers**