# For public site

BASE_URL=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
ADMIN_URL=https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers
DASHBOARD_URL=https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index
BOOKER_API_URL=https://restful-booker.herokuapp.com
ID_LOCATORS_FORM_PAGE_URL=https://proleed.academy/exercises/selenium/selenium-element-id-locators-practice-form.php
NAME_LOCATORS_FORM_PAGE_URL=https://proleed.academy/exercises/selenium/selenium-element-name-locators-practice-form.php
LOCATORS_FORM_PAGE_URL=https://proleed.academy/exercises/selenium/selenium-element-locators-practice-form.php
ADVANCED_LOCATORS_URL=https://practice.expandtesting.com/locators
SELENIUM_WAITS_URL=https://practice.expandtesting.com/slow
FORM_LOCATORS_PRACTICE_URL=https://proleed.academy/exercises/selenium/automation-practice-form-with-radio-button-check-boxes-and-drop-down.php
PRACTICE_TESTING_URL=https://practice.expandtesting.com/

APP_USERNAME=Admin
APP_PASSWORD=admin123

ADMIN_USERNAME=Admin
ADMIN_PASSWORD=admin123

ESS_FIRST_NAME=FN_ESS
ESS_LAST_NAME=LN_ESS
ESS_USER_ID=ESS3145
ESS_USERNAME=ESSuser1
ESS_PASSWORD=ESSpassword123

view_personal_details.path=**/viewPersonalDetails/**
auth_login.path=**/auth/login**
dashboard.path=**/dashboard/**
admin_view_systems_users.path=**/admin/viewSystemUsers**
punch_out.path="**/punchOut"
punch_in.path="**/punchIn"

DB_URL=jdbc:postgresql://localhost:5432/testdb
DB_USER=testuser
DB_PASSWORD=testpass