name: Automation Pipeline

on:
  push:
    branches: [ main, feature/automation-testing ]
  pull_request:
    branches: [ main ]

jobs:

  api-tests:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Run API Tests
      run: mvn test -Dgroups=api

    - name: Generate API Allure Report
      run: mvn allure:report

    - name: Upload API Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: api-allure-report
        path: target/site/allure-maven-plugin


  ui-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Playwright Browsers
      run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

    - name: Run UI Tests
      run: mvn test -Dgroups=ui

    - name: Generate UI Allure Report
      run: mvn allure:report

    - name: Upload UI Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: ui-allure-report
        path: target/site/allure-maven-plugin